config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: {scope: :movie_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy!
    redirect_to list_path(@bookmark.list), status: :see_other
  end

private

  def bookmark_params
    params.require(:bookmark).permit(:name, :comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks.includes(:movie)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render "new", status: :unprocessable_entity
    end
  end

private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: "btn btn-primary mt-4" %>

  <%#= link_to "Delete", pet_path(Pet.last), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" } %>
  <%#= button_to "Delete", pet_path(Pet.last), method: :delete, form: { data: { turbo_confirm: "Are your sure?" } } %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Add a New Bookmark to <%= @list.name %></h1>

  <%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class = "container mt-4">
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary mt-4" %>

  <%#= link_to "Delete", pet_path(Pet.last), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" } %>
  <%#= button_to "Delete", pet_path(Pet.last), method: :delete, form: { data: { turbo_confirm: "Are your sure?" } } %>
<% end %>

app/views/lists/index.html.erb
<h1 class="mb-4">🎬 All Lists</h1>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
  <% @lists.each do |list| %>
    <div class="col">
      <div class="card h-100 shadow-sm border-0">
        <div class="card-body d-flex flex-column justify-content-between">
          <h5 class="card-title"><%= list.name %></h5>
          <%= link_to "View list 🎥", list_path(list), class: "btn btn-outline-primary mt-3" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="mt-4">
  <%= link_to "➕ Create a new list", new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<h1>Add a New List</h1>

  <%= render "form" %>

app/views/lists/show.html.erb
<h1 class="my-4"><%= @list.name %></h1>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
  <% @bookmarks.each do |bookmark| %>
    <div class="col">
      <div class="card h-100 shadow-sm">
        <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title, class: "card-img-top" %>

        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.comment %></p>
        </div>

        <div class="card-footer d-flex justify-content-between">
          <%= link_to "Delete", list_bookmark_path(@list, bookmark),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "btn btn-sm btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="mt-4 d-flex gap-2">
  <%= link_to "← Back to all lists", lists_path, class: "btn btn-outline-primary" %>
  <%= link_to "➕ Add a new Bookmark", new_list_bookmark_path(@list), class: "btn btn-primary" %>
</div>

app/views/movies/index.html.erb
<h1>Movies list</h1>